version: '3.3'
services:
  web:
       image: php:7.3-apache
#       container_name: php73
       build:
            context: ./dockerfiles
            dockerfile: php73.docker
       volumes:
          - ./html:/var/www/html
          - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf
       links:
       - "db:database"
       ports:
          - 80
       environment:
         WWWUSER: borapedi
         WWWGROUP: borapedi    
       depends_on:
         - db
         - nginx
  db:
    container_name: db
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: 29uHIqY8duH3
      MYSQL_DATABASE: borapedi_food
      MYSQL_USER: borapedi_user
      MYSQL_PASSWORD: 29uHIqY8duH3
    ports:
     - "3306:3306"
    logging:
      driver: syslog
      options:
        tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
    restart: on-failure
    volumes:
     - ${PWD}/mariadb:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
